services:
  stardew-analyzer:
    image: ghcr.io/tbg-scrat/stardew-analyser:latest
    container_name: stardew-analyzer
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - /path/to/your/StardewValley/Saves:/saves:ro
